config/routes.rb
Rails.application.routes.draw do


  get 'users/sign_up', to: "users#new"
  post 'users', to: "users#create"

  resources :sessions, only: [:create, :destroy]
    get 'users/sign_in', to: 'sessions#new'

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def authenticate_user!
    redirect_to users_sign_in_path unless helpers.logged?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(email: params[:user][:email],
      password: params[:user][:password])
      if @user.present?
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Has ingresado'
      else
        redirect_to root_path, alert: 'Tus credenciales no son válidas'
      end

    end

    def new
      @user = User.new
    end


    def destroy
      reset_session
      redirect_to root_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

def current_user
  if logged?
    User.find(session[:user_id])
  else
    false
  end
end

def logged?
  session[:user_id].present? ? true : false
end

end

app/views/home/index.html.erb
<div class="text-center">
  <br>
  <%= link_to 'Registrar', users_sign_up_path,  :class => 'btn btn-success' %><br>
  <br>
  <%= link_to 'Acceder', users_sign_in_path,  :class => 'btn btn-info' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pictory</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


</head>

<body>

  <% flash.each do |key, value| %>
       <div class="alert alert-<%= key %>"><%= value %></div>
     <% end %>

  <% if logged? %>
  Bienvenido <%= current_user.name %>
  <% end %>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-inverse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav ">
          <!-- class="active" -->
          <li><%= link_to 'Index', root_path %></li>
          <% if logged? %>
          <li><%= link_to "salir", session_path(current_user), method: :delete %></li>
          <% else %>
          <li><%= link_to 'Registrar', users_sign_up_path %></li>
          <li><%= link_to 'Acceder', users_sign_in_path %></li>
          <% end %>
        </ul>


      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<div class="container text-center">
<h1>BIENVENIDO</h1>
</div>

  <%= yield %>

  <!-- JQuery -->
  <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

app/views/users/new.html.erb
<div class="container text-center">
<h1>Ingrese Los Datos</h1>

<%= form_with(model: @user) do |f| %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>

<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>

<div class="actions"><%= f.submit "Sign Up", :class => 'btn btn-success' %></div>
<% end %>

</div>